[project]
name = "mcp"
version = "0.1.0"
description = "MCP server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.3",
]

[tool.uv.workspace]
members = ["client/mcp-client"]
